config/routes.rb
Rails.application.routes.draw do
  root "lists#index"
  resources :lists do
    resources :bookmarks, only: [:create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates_uniqueness_of :movie_id, scope: :list_id
  validates :comment, length: { minimum: 6 }, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show]
  def index
    @lists = List.all
  end

  def show
    @movies = @list.movies
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
    # if @list.save
    #   redirect_to list_path(@list)
    # else
    #   render :new, status: :unprocessable_entity
    # end
  end



  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<section>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80);">
  <div class="container">
    <h1>Bring your <strong>watchlists</strong> to the next level!</h1>
    <p>Change your life and create one yourself.</p>
    <%= link_to "Write a story", "#section2", class: "btn btn-ghost" %>
  </div>
</div>

</section>
<section class="" id="section2">
<h1>All existing lists</h1>
<% @lists.each do |list| %>
  <%= link_to list.name, list_path(list) %><br>
<% end %>

 <br> <%= link_to "+Add new list",  new_list_path %>
</section>

app/views/lists/new.html.erb
<div class="mx-auto mt-5" style="width: 250px">
<h1>Create list</h1>
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>
  <%= link_to "go back",lists_path %>
</div>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<% if @movies %>
  <% @movies.each do |movie| %>
    <%= movie.title %><br>
    <image src="(<%= movie.poster_url %>)">
    <%# <%= link_to "remove", bookmark_path(@bookmark),
              data: { turbo_method: :delete, turbo_confirm: "U sure?!" } %>
  <% end %>
<% end %>

  <%# <%= link_to "+Add movies to the list", list_id_bookmarks_path %>

  <%= link_to "go back",lists_path %>

  <%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>